# Links:
# - Customization options information:
#   https://changelog.seapagan.net/usage/config_file/#options
# - Example CHANGELOG config file:
#   https://changelog.seapagan.net/usage/config_file/#real-world-example
#   Example CHANGELOG file created with the markdown CHANGELOG generator:
#    https://github.com/seapagan/github-changelog-md/blob/main/CHANGELOG.md

[changelog_generator]

## REQUIRED:
github_pat = "1234567890"

## OPTIONAL - uncomment as needed:
#schema_version = "1"
#unreleased = true
#quiet = false
#depends = true
#contrib = false
#skip_releases = ["1.2.3", "1.2.4"]
#extend_sections = [
#    { title = "Testing", label = "testing" },
#    { title = "Security", label = "security" },
#]
#extend_sections_index = 3
#rename_sections = [{ old = "Enhancements", new = "New Features" }]
#date_format = "%d %B %Y"
#
#
#item_order = "oldest_first"
#ignore_items = [123, 456]
#
#
#extend_ignored = ["testing"]
#allowed_labels = ["question"]
#ignored_users = ["pre-commit-ci[bot]"]
#max_depends = 15
#show_patch = false
#intro_text = """
#This is a log of all the changes that have been made to the project since the
#first release. It is automatically generated for each release.
#"""
#yanked = [
#    { release = "1.3.0", reason = "Ooooh, nasty nasty bug - use 1.3.1 instead!!!" }
#]
#
#[[changelog_generator.release_text]]
#release = "1.4.0"
#text = "This is a paragraph for the 1.4.0 release."
#
#[[changelog_generator.release_text]]
#release = "unreleased"
#text = """
#These are the changes that have been made to the main repository since the last
#release.
#"""
#
#[[changelog_generator.release_overrides]]
#release = "1.3.5"
#text = """
#
#**Replacement Text**
#
#This is **replacement text** for the release notes of version 1.3.5.
#
#No autogenerated text will be included in the release notes for this version.
#"""